ART: Fix run-test invocation for jvm tests
Add check in testrunner.py to conditionally add "--compact-dex-level".

Add check in run-test to warn if the test argument is missing to avoid
cryptic failure.

Test: art/test.py --host --jvm -r -t 526
Change-Id: I73c6f9654656ada79553e536546464e267c66053

diff --git a/test/run-test b/test/run-test
--- a/test/run-test
+++ b/test/run-test
@@ -441,6 +441,11 @@ while true; do
     fi
 done
 
+if [ "$usage" = "no" -a "x$1" = "x" ]; then
+  echo "missing test to run" 1>&2
+  usage="yes"
+fi
+
 # The DEX_LOCATION with the chroot prefix, if any.
 chroot_dex_location="$chroot$DEX_LOCATION"
 
